on:
  push:
    branches: [main]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: moddy.flatpak
        manifest-path: io.github.charlieqle.Moddy.json
        cache-key: flatpak-builder-${{ github.sha }}
